---
# Unbound handlers

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true

- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
    daemon_reload: true

- name: Reload unbound
  ansible.builtin.command:
    cmd: unbound-control reload
  register: unbound_reload_result
  changed_when: unbound_reload_result.rc == 0
  failed_when: unbound_reload_result.rc != 0
