---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart obsidian-livesync
  community.docker.docker_compose_v2:
    project_src: /opt/obsidian-livesync
    state: present
    pull: "never"
  become: true
